package com.revature.post_players;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

@Data
@DynamoDBTable(tableName = "players")
public class Player {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String lastname;

    @DynamoDBAttribute
    private String username;

    @DynamoDBAttribute
    private int wins;

    @DynamoDBAttribute
    private int losses;
}
